### ISSUE TITLE
Hello World to run the app

### ISSUE THREAD

**Issue by ChristianKniep** [Bad-Belzig/smart-village-app-app#2]
Following the documentation in `docs/INDEX.md` I am struggeling to get the app going. 
## Install

I needed to install the expo client, that part was easy.

```bash
npm install --global expo-cli
```

## Config

I figured that I need to setup an account at [sentry.io](sentry.io), create a project and add it to the configuration.

I changed the `src/config/secrets` like this (in addition to commented the `...` at the end)
```json
sentryApi: {
      config: {
        authToken: 'aabbccddee',
        organization: 'my-org',
        project: 'smart-village-app'
      },
      dsn: 'https://some-url-from-sentry'
}
```
I still get this error tho
```bash
npm run ios                                                                                                                                          git:(master|…

> ios
> expo start --ios

WARNING: expo-cli has not yet been tested against Node.js v18.3.0.
If you encounter any issues, please report them to https://github.com/expo/expo-cli/issues

expo-cli supports following Node.js versions:
* >=12.13.0 <15.0.0 (Maintenance LTS)
* >=16.0.0 <17.0.0 (Active LTS)

Error reading Expo config at ~/src/github.com/Bad-Belzig/smart-village-app-app/app.config.js:

Cannot read properties of undefined (reading 'sentryApi')
```

What am I missing?

**Comment by donni106** [comment]
Hi @ChristianKniep, maybe one thing is missing I can think of directly. The `secrets.js` file need to "connect" with the `slug` in `app.json`.

<img width="881" alt="image" src="https://user-images.githubusercontent.com/1942953/188421280-e91d7dcb-5e63-4720-ab9b-6d4e4eee2f99.png">

So maybe `localhost` needs to be changed to `smart-village-app` as `app.config.js` accesses per `secrets[namespace].sentryApi` (and `namespace = config.slug`)?
